server:
  port: 8080
  contextPath: /

  
spring:
  profiles: default
  http:
    multipart:
      maxFileSize: 10MB   
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/codechallenge_cdcy
    username: cdcy
    password: QJUkM5I1P0Vec3W4g1NV
    driver.class: org.postgresql.Driver
    
# Hikari
hikari:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/codechallenge_cdcy
    username: cdcy
    password: QJUkM5I1P0Vec3W4g1NV
    maximumPoolSize: 5